const assert=require('assert'); const v=require('../../skills/shared/scripts/validate_prompt_payload.cjs');
const exact='汉'.repeat(2700), over='汉'.repeat(2701);
assert.equal(v.count('😀汉'),2); assert(v.validate('## Part 1\n'+exact,'character').ok); assert(!v.validate('## Part 1\n'+over,'character').ok);
assert(v.validate('参考图映射：无\n头\n## 场景变化线\n- 变体1提示词：'+ '汉'.repeat(1200),'scene').ok); assert(!v.validate('参考图映射：无\n头\n## 场景变化线\n- 变体1提示词：'+ '汉'.repeat(1201),'scene').ok);
assert(v.validate('## 第一页\n'+exact,'storyboard').ok); assert(!v.validate('## 第一页\n'+over,'storyboard').ok);
assert(v.validate('## S01-01\n'+ '汉'.repeat(1200),'video').ok); assert(!v.validate('## S01-01\n'+ '汉'.repeat(1201),'video').ok);
assert(!v.validate('## Part 1\n裸露','character').ok); console.log('PASS: prompt payload validator boundaries');
for (const marker of ['原文含裸露','事实含半身','冻结对白：缺手脚','用户提供私密部位']) assert(!v.validate('## Part 1\n'+marker,'character').ok);
assert(!v.validate('无 Part 标题','character').ok);
const scene='题材：元数据\n参考图映射：无\n生成规格：4:3\n构图与空间关系：空间\n## 变化线\n- 变体 1 提示词：'+ '汉'.repeat(1200)+'\n- 变体 2 提示词：'+ '汉'.repeat(1201);
const sr=v.validate(scene,'scene'); assert(!sr.ok && sr.units.some(x=>x.id==='variation-2'));
assert(v.validate('## 第一页\n汉','storyboard').ok); assert(v.validate('无页标题但有正文','storyboard').ok);
assert(v.validate('合并视频正文','video').ok); assert(v.validate('## S01-01\n汉\n## S01-02\n汉','video').ok);
assert(!v.validate('## S01-01\n冻结对白裸露','video').ok); console.log('PASS: prompt payload safety/unit coverage');
const shared='共享规格'+ '汉'.repeat(2600);
assert(!v.validate(shared+'\n# 文档标题\n## 第一页\n'+ '汉'.repeat(100),'storyboard').ok);
assert(!v.validate(shared+'\n# 文档标题\n## S01-01\n'+ '汉'.repeat(100),'video').ok);
const scene2='参考图映射：无\n## 场景变化线\n- 变体 1 提示词：'+ '汉'.repeat(10)+'\n- 本体保持：元数据\n- 变体 2 提示词：'+ '汉'.repeat(20);
const s2=v.validate(scene2,'scene'); assert.equal(s2.units.find(x=>x.id==='variation-1').count,10); assert.equal(s2.units.find(x=>x.id==='variation-2').count,20);
console.log('PASS: shared prefix and scene metadata boundaries');
const scene3='参考图映射：无\n## 场景变化线\n- 变体 1 提示词：汉汉\n## 关键道具\n道具描述';
const s3=v.validate(scene3,'scene'); assert.equal(s3.units.find(x=>x.id==='variation-1').count,2);
console.log('PASS: scene subsection boundary');
